[[repo]]
    org = "jotes"
    name = "android-components"
    branch = "master"

[[repo]]
    org = "jotes"
    name = "fenix"
    branch = "master"

[[repo]]
    org = "MozillaReality"
    name = "FirefoxReality"
    branch = "main"

[[repo]]
    org = "jotes"
    name = "lockwise-android"
    branch = "master"
