basepath = "."

locales = [
  "cs",
  "de",
  "en-GB",
  "es",
  "fr",
  "it",
  "ru",
  "uk",
  "vi",
  "zh-TW",
]
[env]

[[paths]]
  reference = "app/src/main/res/values/stringsTest.xml"
  l10n = "app/src/main/res/values-{android_locale}/stringsTest.xml"






